### ISSUE TITLE
improve incorrect input handling for number guess in guess_the_number.py

### ISSUE THREAD

**Issue by korbdallas** [korbdallas/games#1]
If you enter a letter the application crashes with the following kind of error 

```
Hello what is your name? 
Mike
Well, Mike, I am thinking of a number between 1 and 20

Take a guess
k
Traceback (most recent call last):
  File "/home/mcolombo/Documents/python/git/games/guess_the_number.py", line 34, in <module>
    guessing_game()
  File "/home/mcolombo/Documents/python/git/games/guess_the_number.py", line 19, in guessing_game
    guess=int(input())
ValueError: invalid literal for int() with base 10: 'k'
```

When entering a blank response the following error is seen 

```
Hello what is your name? 
Mike
Well, Mike, I am thinking of a number between 1 and 20

Take a guess

Traceback (most recent call last):
  File "/home/mcolombo/Documents/python/git/games/guess_the_number.py", line 34, in <module>
    guessing_game()
  File "/home/mcolombo/Documents/python/git/games/guess_the_number.py", line 19, in guessing_game
    guess=int(input())
ValueError: invalid literal for int() with base 10: ''
```

**Comment by korbdallas** [comment]
Fixed with commit 5192ae8
